name: Validation Environment
on:
  pull_request:
    types: [opened, synchronize ]
    branches: [deploy]
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write
jobs:
  build-heritage-staging:
    name: Initial Review Phase 🧵
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout code 🧳
        uses: actions/checkout@v4.1.7
      - name: Setup Node 🍳
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
      - name: setup pnpm 👨‍💻
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.6.0
          run_install: false
      - name: Install pnpm 💠
        run: pnpm install --no-frozen-lockfile
      - name: build Application 📦
        run: pnpm build